#!/bin/bash

anaconda_installer_path=~/DML/anaconda/Anaconda2-5.2.0-MacOSX-x86_64.sh
anaconda_installation_path=~/anaconda2
conda_environment_for_jupyter_python2=jupy27
conda_environment_for_jupyter_python3=jupy36

if ! grep -e "export PATH=.*/anaconda2/bin:\$PATH" ~/.bash_profile; then
  echo "Anaconda path not found in ~/.bash_profile"
  echo "I'm expecting it to exist, as I am a refresh script"
  echo "Besides, running Anaconda installer with -b does not add it"
  exit 1
fi

rm -rf ${anaconda_installation_path}
bash ${anaconda_installer_path} -b -p ${anaconda_installation_path}

conda create --yes -n ${conda_environment_for_jupyter_python2} python=2.7
# shellcheck disable=SC1091
source activate ${conda_environment_for_jupyter_python2}
conda install --yes notebook ipykernel
ipython kernel install --user --display-name "Python 2"
pip install ansible
source install-ansible-dependencies
# shellcheck disable=SC1091
source deactivate

conda create --yes -n ${conda_environment_for_jupyter_python3} python=3.6
# shellcheck disable=SC1091
source activate ${conda_environment_for_jupyter_python3}
conda install --yes notebook ipykernel
ipython kernel install --user --display-name "Python 3"
source install-modules-for-machinelearning
# shellcheck disable=SC1091
source deactivate

source install-missing-dependencies
pip install ansible
source install-ansible-dependencies
