#!/bin/bash
pip install ansible-lint
# for filters:
pip install jmespath
pip install netaddr
pip install passlib
# for Docker:
pip install docker
# for Ansible Tower:
# pip install ansible-tower-cli==3.1.7
pip install ansible-tower-cli
# for Amazon AWS:
pip install boto
pip install boto3
# for Azure:
# pip install azure==2.0.0rc5 msrest msrestazure enum packaging
# for DigitalOcean:
pip install dopy
# for Windows:
pip install pywinrm
# for VMware:
pip install pyvmomi
# for Proxmox:
pip install proxmoxer
# for Hashicorp Vault
pip install hvac
# other:
pip install molecule
