#!/bin/bash
set -e

requested_ansible_version=$1

if [ "${requested_ansible_version}" == "" ]; then
    echo Please provide Ansible version
    exit 1
fi

# in PyPI some package versions, like ansible-1.9.0 have null value, so first filter them out
# shellcheck disable=SC2086
package_url_check_result=$(curl -s https://pypi.org/pypi/ansible/json | jq ".releases | with_entries(select(.value!=[])) | keys | index(["\"${requested_ansible_version}"\"])")

if [ "${package_url_check_result}" == "null" ]; then
    echo "Ansible version ${requested_ansible_version} not found on PyPI"
    exit 1
fi

env_name="ansible-${requested_ansible_version}"

conda remove --yes --name "${env_name}" --all
conda create --yes --name "${env_name}" python=2.7
# shellcheck disable=SC1091
source activate "${env_name}"
pip install ansible=="${requested_ansible_version}"
source install-ansible-dependencies
