#!/bin/bash
set -e

env_name="ansible-devel"

conda remove --yes --name "${env_name}" --all
conda create --yes --name "${env_name}" python=2.7
# shellcheck disable=SC1091
source activate "${env_name}"
pip install pyyaml
pip install pycrypto
pip install jinja2
pip install six
pip install jmespath
pip install git+https://github.com/ansible/ansible.git@devel
source install-ansible-dependencies
