#!/bin/bash

anaconda_installer_path=~/DML/anaconda/Anaconda2-5.2.0-MacOSX-x86_64.sh
anaconda_installation_path=~/anaconda2

if ! grep -e "export PATH=.*/anaconda2/bin:\$PATH" ~/.bash_profile; then
  echo "Anaconda path not found in ~/.bash_profile"
  echo "I'm expecting it to exist, as I am a refresh script"
  echo "Besides, running Anaconda installer with -b does not add it"
  exit 1
fi

#### base environment ####

rm -rf ${anaconda_installation_path}
bash ${anaconda_installer_path} -b -p ${anaconda_installation_path}

source install-missing-dependencies
pip install nbstripout nbconvert
pip install ansible
source install-ansible-dependencies

#### include ./environments.d ####

while read -r filename
do
    # shellcheck disable=SC1090
    source "${filename}"
done < <(find -L ./environments.d -type f)
