#!/bin/bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$(uname -s)" == "Darwin" ]; then
    readlink_executable=greadlink
else
    readlink_executable=readlink
fi

environment_name=$(basename "$(${readlink_executable} --canonicalize "${BASH_SOURCE[0]}")")

# shellcheck disable=SC1091
source deactivate

conda remove --yes --name "${environment_name}" --all
conda create --yes -n "${environment_name}" anaconda python=3.6
# shellcheck disable=SC1091
source activate "${environment_name}"

# shellcheck disable=SC1090
source "${current_directory}/../install-missing-dependencies"
# shellcheck disable=SC1090
source "${current_directory}/../install-modules-for-data-science"

# shellcheck disable=SC1091
source deactivate
