#!/bin/bash

if [ "$(uname -s)" == "Darwin" ]; then
    readlink_executable=greadlink
else
    readlink_executable=readlink
fi

environment_name=$(basename "$(${readlink_executable} --canonicalize "${BASH_SOURCE[0]}")")

# shellcheck disable=SC1091
source deactivate

conda remove --yes --name "${environment_name}" --all
conda create --name "${environment_name}" --clone _python_27
# shellcheck disable=SC1091
source activate "${environment_name}"

conda install --yes notebook ipykernel
ipython kernel install --user --name "${environment_name}" --display-name "Python 2.7 (devel)"

pip install pytest
pip install setuptools
pip install coverage
pip install pytest-cov
pip install boto3 moto
pip install pyyaml

# shellcheck disable=SC1091
source deactivate
