#!/bin/bash

if [ "$(uname -s)" == "Darwin" ]; then
    readlink_executable=greadlink
else
    readlink_executable=readlink
fi

environment_name=$(basename "$(${readlink_executable} --canonicalize "${BASH_SOURCE[0]}")")

# shellcheck disable=SC1091
source deactivate

conda remove --yes --name "${environment_name}" --all
conda create --yes -n "${environment_name}" python=3.7
# shellcheck disable=SC1091
source activate "${environment_name}"

pip install boto3
# pip install pyyaml  # broken as of 2018-07-05

# shellcheck disable=SC1091
source deactivate
